import React, { useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import { parseExcelFile } from "../utils/fileUtils";
import { saveImportData } from "../utils/storage";
const FileUpload = () => {
  const fileInput = useRef(null);
  const [dragActive, setDragActive] = useState(false);
  const [error, setError] = useState("");
  const navigate = useNavigate();

  const handleFile = async (file) => {
    setError("");
    try {
      const data = await parseExcelFile(file);
      await saveImportData(data);
      navigate("/manage-boxes");
    } catch (e) {
      setError(
        "Failed to parse file. Please upload a valid Amazon box content file."
      );
    }
  };

  const handleDrop = (e) => {
    e.preventDefault();
    setDragActive(false);
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      handleFile(e.dataTransfer.files[0]);
    }
  };

  const handleFileChange = (e) => {
    if (e.target.files && e.target.files[0]) {
      handleFile(e.target.files[0]);
    }
  };

  return (
    <div className="card shadow-sm border-0 p-4 text-center">
      <div className="mb-3">
        <i className="bi bi-cloud-arrow-up-fill display-4 text-primary"></i>
      </div>
      <h5 className="mb-3">Upload Amazon Box Content File</h5>
      <p className="text-muted mb-4">
        Only .xlsx or .csv files generated by Amazon are supported.
      </p>

      <div
          className={`upload-area p-5 text-center border border-3 rounded-4 bg-light ${dragActive ? "border-primary bg-white" : ""}`}
          onDragOver={e => { e.preventDefault(); setDragActive(true); }}
          onDragLeave={e => { e.preventDefault(); setDragActive(false); }}
          onDrop={handleDrop}
          onClick={() => fileInput.current.click()}
          style={{ cursor: "pointer" }}
        >
          <input
            ref={fileInput}
            type="file"
            accept=".xlsx,.xls,.csv"
            className="d-none"
            onChange={handleFileChange}
          />
          <img
            src="https://cdn-icons-png.flaticon.com/512/724/724933.png"
            alt="Upload"
            style={{ width: 80, marginBottom: 16, opacity: 0.7 }}
          />
          <h4 className="mb-1">Upload Amazon Box Content File</h4>
          {/* <p className="mb-4 text-muted">
            Drag & drop your <b>.xlsx</b> or <b>.csv</b> file here, <br />or <span className="text-primary">click to browse</span>
          </p>
          <div className="small text-secondary">
            Only Amazon-generated box content templates are supported.
          </div> */}
        </div>
{/* 
      <button className="btn btn-primary px-4" onClick={triggerFileInput}>
        Select File
      </button> */}
      {error && <div className="alert alert-danger mt-3">{error}</div>}
    </div>
  );
};

export default FileUpload;
